<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link href="style.css" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&family=Prompt:wght@200&family=Roboto:ital,wght@1,300;1,400&family=Varela+Round&display=swap" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

</head>

<body>
  
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color:rgb(0, 0, 0);">

    <div class="container-fluid"border:none>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#try">TRY</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#catch">CATCH</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#finally">FINALLY</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#throw">THROW</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#throws">THROWS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#ude">USER DEFINED EXCEPTIONS</a>
          </li>
          <div class="pull-right">
          <li class ="nav-item dropdown">
            <a class ="nav-link dropdown-toggle nav navbar-nav" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Members
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="https://www.linkedin.com/in/ramgopal-raula-131a11a7">Ramgopal Raula 20051430</a></li>
              <li><a class="dropdown-item" href="https://www.linkedin.com/in/ishan-ayush-378a50168">Ishan Ayush 20051414</a></li>
              <li><a class="dropdown-item" href="https://www.linkedin.com/in/ananya-das-3b739a239/">Ananya Das 20051450</a></li>
              <li><a class="dropdown-item" href="https://www.linkedin.com/in/ayush-negi-93351b204">Ayush Negi 20051452</a></li>
            </ul>
          </li>
        </ul>
      </div>
      </div>
    </div>
  </nav>
  <h1>WEB TECHNOLOGY PROJECT</h1>
    <div class = "main">
    <h2 id="try"></h2>
    <br><br><br>
    <h2>Try</h2>

    <h4>The try block contains set of statements where an exception can occur.</h4>

    <p>Java try block is used to enclose the code that might throw an exception. It must be used within the method. If
      an exception occurs at the particular statement in the try block, the rest of the block code will not execute.
      So, it is recommended not to keep the code in try block that will not throw an exception. Java try block must be
      followed by either catch or finally block.</p>

    <div class = "inner">
      try <br>&nbsp&nbsp{<br>
      &nbsp&nbsp&nbsp&nbsp&nbsp// statements<br>
      &nbsp&nbsp}<br> &nbsp&nbspcatch (error) <br>&nbsp&nbsp{<br>
      &nbsp&nbsp&nbsp&nbsp// statements<br>
      &nbsp&nbsp} <br>finally <br>&nbsp&nbsp{<br>
      // statements<br>
      &nbsp&nbsp}<br>
    </div>

    <h3>Example</h3>


    <div class = "inner">
      class Example<br>
      &nbsp{<br>
      &nbsp&nbsp&nbsp public static void main(String[] args)<br>
      &nbsp&nbsp{<br>
      try<br>
      &nbsp&nbsp{<br>
      &nbsp&nbsp&nbsp&nbsp&nbsp int n1=5;<br>
      &nbsp&nbsp&nbsp&nbsp&nbsp int result=n1/0;<br>
      &nbsp&nbsp&nbsp&nbsp System.out.println("Division ="+result);<br>
      }<br>
      &nbsp&nbsp&nbsp&nbspcatch(ArithmeticException e)<br>
      {<br>
      &nbsp&nbsp&nbspSystem.out.println("Error:Divide by zero not allowed");<br>
      &nbsp&nbsp}<br>
      &nbsp}<br>
      }<br>
    </div>
  </div>
  <br><br>
  <hr style="color:rgb(253, 253, 253); height: 3px;">
  <div class = "main">
    <h2 id="catch"></h2>
    <br>
    <h2>Catch</h2>

    <h4> Catch block is executed when error occurs in the try block.</h4>

    <p>Java catch block is used to handle the Exception by declaring the type of exception within the parameter. The
      declared exception must be the parent class exception ( i.e., Exception) or the generated exception type.
      However,
      the good approach is to declare the generated type of exception.</p>

      <div class = "inner">
      catch (Exception e)<br>{<br>
      //code to handle exception e<br>
      }<br>
    </div>
  </div>
  <br><br>
  <hr style="color:rgb(253, 253, 253); height: 3px;">
    <div class = "main">
    <h2 id="finally"></h2>
    <br>
    <h2>Finally</h2>

    <h4>A finally keyword is used to create a block of code that follows a try block.</h4>

    <p>Java finally block is a block used to execute important code such as closing the connection, etc. Java finally
      block
      is always executed whether an exception is handled or not. Therefore, it contains all the necessary statements
      that
      need to be printed regardless of the exception occurs or not.</p>

      <div class = "inner">
      try <br>&nbsp&nbsp&nbsp{<br>
      &nbsp&nbsp&nbsp&nbsp&nbsp// statements<br>
      &nbsp&nbsp&nbsp}<br> &nbsp&nbsp&nbspcatch (error) <br>&nbsp&nbsp&nbsp{<br>
      &nbsp&nbsp&nbsp&nbsp// statements<br>
      &nbsp&nbsp&nbsp}<br> &nbsp&nbsp&nbsp&nbspfinally<br> &nbsp&nbsp&nbsp&nbsp&nbsp{<br>
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp// statements<br>
      &nbsp&nbsp&nbsp&nbsp&nbsp}<br>
    </div>
  </div>
  <br><br>
  <hr style="color:rgb(253, 253, 253); height: 3px;">
    <div class = "main">
    <h2 id="throw"></h2>
    <br>
    <h2>Throw</h2>

    <h4>The throw keyword is used to throw an exception explicitly.</h4>

    <div class = "inner">
      throw Instance
    </div>

    <h3>Example</h3>

    <div class = "inner">
      throw new ArithmeticException("/ by zero");
    </div>
  </div>
  <br><br>
  <hr style="color:rgb(253, 253, 253); height: 3px;">
    <div class = "main">
    <h2 id="throws"></h2>
    <br>
    <h2>Throws</h2>

    <h4>Throws in Java which is used in method signature indicate that this method might throw one of the listed type
      exceptions.</h4>

      <div class = "inner">
      throw Instance
    </div>

    <h3>Example</h3>

    <div class = "inner">
      throw new ArithmeticException("/ by zero");
    </div>
  </div>
  <br><br>
  <hr style="color:rgb(253, 253, 253); height: 3px;">
    <div class = "main">
    <h2 id="ude"></h2>
    <br>
    <h2>User Defined Exception</h2>
    <h4>
      Java provides us the facility to create our own exceptions which are basically derived classes of Exception.
      Creating our own Exception is known as a custom exception or user-defined exception. Basically, Java custom
      exceptions are used to customize the exception according to user needs. In simple words, we can say that a
      User-Defined Exception or custom exception is creating your own exception class and throwing that exception
      using
      the ‘throw’ keyword.
    </h4>
    <h3>Example</h3>

    <div class = "inner">

      // A Class that represents use-defined exception<br>

      class MyException extends Exception <br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{<br>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsppublic MyException(String s)<br>
      <br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{<br>
      // Call constructor of parent Exception
      super(s);
      &nbsp&nbsp&nbsp&nbsp<br>&nbsp&nbsp&nbsp&nbsp}<br>
      &nbsp&nbsp&nbsp&nbsp }<br>

      // A Class that uses above MyException
      public class Main <br>&nbsp&nbsp&nbsp&nbsp&nbsp{<br>
      // Driver Program<br>
      public static void main(String args[])
      {<br>
      try {<br>
      // Throw an object of user defined exception<br>
      throw new MyException("Wt Project");<br>
      }<br>
      catch (MyException ex) <br>{<br>
      System.out.println("Caught");<br>

      // Print the message from MyException object<br>
      System.out.println(ex.getMessage());<br>
      }<br>
      }<br>
      }<br>
    </div>
  
</body>

</html>